POST http://localhost:8080/api/users/authenticate
Content-Type: application/json

{
  "username": "carlos.montoya.rdgz@gmail.com",
  "password": "sipirili"
}

###

GET http://localhost:8080/api/puntajes/search/findByLeccion_ClaveOrderByPuntajeDesc?leccion=letras&
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtaW5vSldUIiwic3ViIjoiY2FybG9zLm1vbnRveWEucmRnekBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTc0NTA5MTc2LCJleHAiOjE1NzUxMDkxNzZ9.L5elqt3TR8BPS8dt4r3QFUn9C7JoHuxWo1uqehHrQl4rhCeP8oJi08Tggf6WyV4_6OQRUVlAlf0xnctoj0nGkg

###

GET http://localhost:8080/api/puntajes/search/findFirstByLeccion_ClaveAndUsuarioOrderByPuntajeDesc?leccion=puntuacion&usuario=carlos.montoya.rdgz@gmail.com&
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtaW5vSldUIiwic3ViIjoiY2FybG9zLm1vbnRveWEucmRnekBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTc0NTA2MDI2LCJleHAiOjE1NzUxMDYwMjZ9.CwTcWulTi5ULQ29X-OW1Ea8ZSWM5enMkr9SiAN9LZ20nMAaaCcuLiGtWcPjwx_H-EkWKj4YP0QxLqEbPb-sOKg

###

POST http://localhost:8080/api/puntajes
Content-Type: application/json

{
  "leccion": "http://localhost:8080/api/lecciones/7",
  "usuario": "carlos5",
  "puntaje": 5
}

###
